### ISSUE TITLE
Resource types do not have inheritence/is-a relationship between versions in ARM

### ISSUE THREAD

**Issue by johanste** [devigned/profile-playground#6]
RPC does not guarantee that two versions of a resource have any kind of relationship that can be expressed as an inheritence in traditional OO sense. In most cases, the models are supersets of each other, but that can still not be modeled correctly using inheritence in a language like C#.

Consider VirtualMachineV1, which has a property storageProfile of complex type StorageProfileV1. VirtualMachineV2 has a property storageProfile of type StorageProgileV2.

If VirtualMachineV2 inherited from VirtualMachineV1, it would imply that you could implicitly upcast an instance of VirtualMachineV2 to VirtualMachineV1, and then assign an instance of StorageProfileV1 to the storageProfile property. Which is not valid.

One can resort to runtime exceptions in cases like this, but that would (IMO) defeat some of the purpose of having a strongly typed language in the first place...

**Comment by devigned** [comment]
Agreed. I took that approach to allow forward projection of interfaces. 

The situation that would cause the runtime error is [here](https://github.com/devigned/profile-playground/blob/master/dotnet/samples/MultiProfileSample.cs#L29), and would occur because of the inability to project an older type to a newer type via the explicit interface implementation [here](https://github.com/devigned/profile-playground/blob/master/dotnet/src/Azure/Mgmt/Microsoft.Compute/2016_06_30/Models/VirtualMachine.cs#L32-L36).

If this trade off is not desirable, we should not build interfaces forward from one version to the next.

/cc @twitchax @sarangan12

**Comment by devigned** [comment]
This has been killed and is updated in master. I'm going to close this issue.
